name: Create v2.0.0 Release

on:
  push:
    branches:
      - v2

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Create and push v2.0.0 tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag v2.0.0
          git push origin v2.0.0

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v2.0.0
          name: "v2.0.0 Release"
          body: "Automatic release of v2.0.0"
          draft: false
          prerelease: false
